analyze -f VHDL    ../../rtl/config/target.vhd
analyze -f VHDL    ../../rtl/config/device.vhd
analyze -f VHDL    ../../rtl/config/config.vhd
analyze -f VHDL    ../../rtl/config/iface.vhd
analyze -f VHDL    ../../rtl/amba/amba.vhd
analyze -f VHDL    ../../rtl/amba/ambacomp.vhd
analyze -f VHDL    ../../rtl/amba/apbmst.vhd
analyze -f VHDL    ../../rtl/amba/ahbmst.vhd
analyze -f VHDL    ../../rtl/amba/ahbstat.vhd
analyze -f VHDL    ../../rtl/amba/ahbtest.vhd
analyze -f VHDL    ../../rtl/amba/ahbram.vhd
analyze -f VHDL    ../../rtl/amba/ahbarb.vhd
analyze -f VHDL    ../../rtl/mctrl/sdmctrl.vhd
analyze -f VHDL    ../../rtl/mctrl/mctrl.vhd
analyze -f VHDL    ../../rtl/uart/dcom_uart.vhd
analyze -f VHDL    ../../rtl/uart/dcom.vhd
analyze -f VHDL    ../../rtl/uart/uart.vhd
analyze -f VHDL    ../../rtl/pci/pci_gr.vhd
analyze -f VHDL    ../../rtl/pci/pci.vhd
analyze -f verilog {../../rtl/eth/device.v ../../rtl/eth/eth_top.v}
analyze -f VHDL    ../../rtl/arith/multlib.vhd
analyze -f VHDL    ../../rtl/arith/mul.vhd
analyze -f VHDL    ../../rtl/arith/div.vhd
analyze -f VHDL    ../../rtl/clkrst/rstgen.vhd
analyze -f VHDL    ../../rtl/tech/tech_generic.vhd
analyze -f VHDL    ../../rtl/tech/tech_virtex.vhd
analyze -f VHDL    ../../rtl/tech/tech_virtex2.vhd
analyze -f VHDL    ../../rtl/tech/tech_atc18.vhd
analyze -f VHDL    ../../rtl/tech/tech_atc25.vhd
analyze -f VHDL    ../../rtl/tech/tech_atc35.vhd
analyze -f VHDL    ../../rtl/tech/tech_fs90.vhd
analyze -f VHDL    ../../rtl/tech/tech_tsmc25.vhd
analyze -f VHDL    ../../rtl/tech/tech_umc18.vhd
analyze -f VHDL    ../../rtl/tech/tech_proasic.vhd
analyze -f VHDL    ../../rtl/tech/tech_axcel.vhd
analyze -f VHDL    ../../rtl/tech/tech_map.vhd
analyze -f VHDL    ../../rtl/cpu/sparcv8.vhd
analyze -f VHDL    ../../rtl/cpu/mmuconfig.vhd
analyze -f VHDL    ../../rtl/cpu/macro.vhd
analyze -f VHDL    ../../rtl/cpu/bprom.vhd
analyze -f VHDL    ../../rtl/cpu/mmu_icache.vhd
analyze -f VHDL    ../../rtl/cpu/mmu_dcache.vhd
analyze -f VHDL    ../../rtl/cpu/mmu_acache.vhd
analyze -f VHDL    ../../rtl/cpu/mmutlbcam.vhd
analyze -f VHDL    ../../rtl/cpu/mmulrue.vhd
analyze -f VHDL    ../../rtl/cpu/mmulru.vhd
analyze -f VHDL    ../../rtl/cpu/mmutlb.vhd
analyze -f VHDL    ../../rtl/cpu/mmutw.vhd
analyze -f VHDL    ../../rtl/cpu/mmu.vhd
analyze -f VHDL    ../../rtl/cpu/mmu_cache.vhd
analyze -f VHDL    ../../rtl/cpu/cachemem.vhd
analyze -f VHDL    ../../rtl/cpu/icache.vhd
analyze -f VHDL    ../../rtl/cpu/dcache.vhd
analyze -f VHDL    ../../rtl/cpu/acache.vhd
analyze -f VHDL    ../../rtl/cpu/cache.vhd
analyze -f VHDL    ../../rtl/cpu/lconf.vhd
analyze -f VHDL    ../../rtl/cpu/fpulib.vhd
analyze -f VHDL    ../../rtl/cpu/fpu_lth.vhd
analyze -f VHDL    ../../rtl/cpu/meiko.vhd
analyze -f VHDL    ../../rtl/cpu/fpu_core.vhd
analyze -f VHDL    ../../rtl/cpu/ioport.vhd
analyze -f VHDL    ../../rtl/cpu/iu.vhd
analyze -f VHDL    ../../rtl/cpu/dsu_mem.vhd
analyze -f VHDL    ../../rtl/cpu/dsu.vhd
analyze -f VHDL    ../../rtl/cpu/proc.vhd
analyze -f VHDL    ../../rtl/cpu/wprot.vhd
analyze -f VHDL    ../../rtl/cpu/irqctrl.vhd
analyze -f VHDL    ../../rtl/cpu/timers.vhd
analyze -f VHDL    ../../rtl/cpu/mcore.vhd
analyze -f VHDL    ../../rtl/top/demo_soc.vhd
